fixed relative paths bug

diff --git a/timely b/timely
--- a/timely
+++ b/timely
@@ -30,14 +30,14 @@ function load_config {
     done < "/usr/local/etc/timely/.preferences"
 }
 
-usage="usage: timely <add | remove | set> [executable | minutes]"
+usage="usage: timely <add | remove | set | preferences> [executable | minutes]"
 usage_add="usage: timely add [executable]"
 usage_remove="usage: timely remove [full path to executable]"
 usage_list="usage: timely list"
 
 if [ $# -lt 1 ]; then
     echo "$usage"
-    exit
+    exit 1
 fi
 
 load_config
@@ -45,17 +45,18 @@ load_config
 
 if ! [[ "$time" =~ ^[0-9]+$ ]] || ! [[ "$extra_time" =~ ^[0-9]+$ ]] ||  [ "$time" -eq -1 ] || [ "$extra_time" -eq -1 ]; then
     echo "aborting - bad config file"
-    exit
+    exit 1
 fi
 
 if [ $1 == "add" ]; then
-    if [ $# -eq 2 ] && [ -f "$2" ] && [ -x "$2" ]; then       
-        path=`find $PWD -type f | grep "\/$2$"`
+    if [ $# -eq 2 ] && [ -f "$2" ] && [ -x "$2" ]; then
+        path=$(cd "$(dirname "$2")" && pwd)/$(basename "$2")
+        # path=`find $PWD -type f | grep "\/$2$"`
         escapedPath=$(echo $path | sed 's_/_\\/_g')
 
         if grep -q "$path" "$main_path/.timelies"; then
             echo "Timely already exists"
-            exit
+            exit 1
         fi
 
         mv "$2" "$2-real"
@@ -85,7 +86,9 @@ elif [ $1 == "remove" ]; then
             rm "$2"
             mv "$2-real" "$2"
             echo "Restrictions removed for $(basename $2)"
-         fi
+        else
+            echo "Timely not found"
+        fi
     else
         echo "$usage_remove"
     fi
